/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.globemed.patterns.builder;

import com.globemed.models.*;
import java.util.List;

/**
 *
 * @author Hansana
 */
public class ReportDirector {

    public Report buildTreatmentReport(Patient patient, Appointment appointment, List<Bill> bills) {
        TreatmentReportBuilder builder = new TreatmentReportBuilder();

        return builder
                .setTitle("Patient Treatment Summary")
                .setPatient(patient)
                .setAppointment(appointment)
                .addBills(bills)
                .setSummary("Treatment completed successfully. Patient advised to follow up as scheduled.")
                .setFooter("This report is confidential and intended for medical professionals only.")
                .build();
    }

    public Report buildFinancialReport(Patient patient, List<Bill> bills) {
        FinancialReportBuilder builder = new FinancialReportBuilder();

        return builder
                .setTitle("Patient Financial Statement")
                .setPatient(patient)
                .addBills(bills)
                .setSummary("All services have been documented. Please remit payment as per payment terms.")
                .setFooter("For billing inquiries, please contact our billing department.")
                .build();
    }

    public Report buildDiagnosticReport(Patient patient, Appointment appointment, Bill bill) {
        DiagnosticReportBuilder builder = new DiagnosticReportBuilder();

        return builder
                .setTitle("Diagnostic Results Report")
                .setPatient(patient)
                .setAppointment(appointment)
                .addBill(bill)
                .addCustomSection("Test Results", "Laboratory results and diagnostic findings will be documented here by the examining physician.")
                .setSummary("Diagnostic procedures completed. Results to be reviewed by attending physician.")
                .setFooter("Report generated by GlobeMed Healthcare Management System")
                .build();
    }

    public Report buildCustomReport(String title, Patient patient, Appointment appointment,
            List<Bill> bills, String summary, String reportType) {
        ReportBuilder builder;

        switch (reportType.toUpperCase()) {
            case "TREATMENT":
                builder = new TreatmentReportBuilder();
                break;
            case "FINANCIAL":
                builder = new FinancialReportBuilder();
                break;
            case "DIAGNOSTIC":
                builder = new DiagnosticReportBuilder();
                break;
            default:
                builder = new TreatmentReportBuilder(); // Default to treatment report
        }

        return builder
                .setTitle(title)
                .setPatient(patient)
                .setAppointment(appointment)
                .addBills(bills)
                .setSummary(summary)
                .setFooter("Generated by GlobeMed Healthcare Management System")
                .build();
    }
}
